### ISSUE TITLE
Store `DataProcessor` normalisation mapping parameters as a list, not `param1`/`param2`

### ISSUE THREAD

**Issue by tom-andersson** [tom-andersson/deepsensor#40]
Parameters for normalisation mappings are computed by [DataProcessor.get_norm_params](https://github.com/tom-andersson/deepsensor/blob/d1ce7ac2e6d538d84d046d76d1335b94a22e01c7/deepsensor/data/processor.py#L164) (if not pre-computed), and are stored in the `DataProcessor.norm_params` like this:
```
'air': {'method': 'mean_std',
         'param1': 281.255126953125,
         'param2': 16.320409774780273},
```

The above config assumes there are only two parameters for a normalisation method. This is true for the two existing methods (`"mean_std"` and `"min_max"`), but might not be true in general; I suggest we update the `DataProcessor` config to have a single `params` entry with a list of parameters.

**Comment by patel-zeel** [comment]
Hi @tom-andersson,

I have looked into this since resolving this before #39 may be more manageable. [Here](https://github.com/tom-andersson/deepsensor/compare/main...patel-zeel:single_params?diff=unified) is the full summary of changes. If someone is not working on this, I can open a PR, and we can discuss the changes in the PR.

**Comment by tom-andersson** [comment]
Hey @patel-zeel, these changes LGTM, please open a PR. Thanks so much!

**Comment by patel-zeel** [comment]
Great! Thanks a lot for your appreciation! I have opened a PR now.

**Comment by tom-andersson** [comment]
Thanks @patel-zeel!
